env:
  source_num_envs: 64
  source_num_levels: 100
  target_num_envs: 64
  target_num_levels: 200

ppo:
  num_steps: 1000000
  ppo_batch_size: 128
  unroll_length: 16
  ppo_lr: 5.e-4
  gamma: 0.999
  ppo_clip_param: 0.2
  num_gradient_steps: 3
  value_loss_coef: 0.5
  entropy_coef: 0.01
  lambd: 0.95
  max_grad_norm: 0.5
  use_deep: True

wappo:
  adv_batch_size: 128
  adv_lr: 5.e-4
  num_critic: 5
  use_gp: False
  lambda_gp: 10.0
  weight_clip_param: 0.01
