env:
  num_envs: 64
  num_levels: 1

ppo:
  num_steps: 1000000
  lr_ppo: 5.e-4
  gamma: 0.999
  rollout_length: 256
  num_minibatches: 8
  epochs_ppo: 3
  clip_range_ppo: 0.2
  value_coef: 0.5
  ent_coef: 0.01
  lambd: 0.95
  max_grad_norm: 0.5
  use_impala: True

wappo:
  lr_adv: 5.e-4
  epochs_critic: 5
  clip_range_adv: 0.01
